# Generated by Django 5.1.4 on 2026-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
